id: P010617
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:42.360874
source_metadata:
  id: bdr:W22056
  title: སོག་པོ་རྟ་རྫོང་།
  author: ''
  volumes:
    59afe0fb9265494c9dba39f6d7cadcb7:
      image_group_id: I1KG17136
      title: ''
      volume_number: 1
      total_pages: 346
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
